// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	firestore "randomInsultService/vendor/cloud.google.com/go/firestore"
)

// DataSource is an autogenerated mock type for the DataSource type
type DataSource struct {
	mock.Mock
}

// InitializeDataSource provides a mock function with given fields:
func (_m *DataSource) InitializeDataSource() (*firestore.Client, error) {
	ret := _m.Called()

	var r0 *firestore.Client
	if rf, ok := ret.Get(0).(func() *firestore.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*firestore.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
